server:
  port: 8080


spring:
  application:
    name: main

  datasource:
    url: jdbc:mysql://localhost:3301/webstoreDB
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update


app:
  endpoints:
    management:
      main: /management
      creating: /management/create
      editing: /management/edit

    warehouse:
      main: /warehouse

    catalog:
      main: /catalog
      good-page: /catalog/{id}

    customer:
      cart:
        main: /customer/cart
      feedbacks:
        main: /customer/feedbacks

    mod_auth:
      enter: /mod_auth/enter
      process_login: /mod_auth/process_login
